# --- Websocket handling ---
# Maps the 'Upgrade' header to determine if the connection should stay open 
# ('upgrade') for WebSockets or close ('close') for standard HTTP traffic.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 8080;
    client_max_body_size 0;

    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Host $host;
        
        # Specify that filebrowser should return the HTML unencoded (Disable upstream compression)
        proxy_set_header Accept-Encoding "";


        # --- Proxy websocket configuration ---
        # Force HTTP/1.1 (Mandatory requirement for WebSockets).
        proxy_http_version 1.1;

        # Forward the 'Upgrade' header to the backend if the client requested it.
        proxy_set_header Upgrade $http_upgrade;

        # Set 'Connection' to 'upgrade' or 'close' based on the map rule above.
        proxy_set_header Connection $connection_upgrade;


        # Replace "</body>" with "<script>...</script></body>"
        sub_filter '</body>' '<script src="/branding/injection_custom_progress_bar.js"></script></body>';
        sub_filter_once on;
    }

    location /branding/ {
        alias /branding/;
    }

    #For the progress_bar, to obtain the status.json created in progress_bar_writer.sh
    # status.json changes every 2s — never cache it, always read from disk
    location /status/ {
        alias /data/processed/;
        sendfile off;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        expires -1;

        # If status.json does not exist, return an empty JSON object instead of a 404 error in the client-side JavaScript code web console.
        try_files $uri @status_inactive;
    }

    # Fallback location for when status.json is missing, to avoid 404 errors in the client-side JavaScript code web console.
    location @status_inactive {
        default_type application/json;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        return 200 '{"active": false}';
    }
        
        
}